
# This code reads the CSV of patient data, and 
# saves a histogram of ages to a new file.
# https://docs.opensafely.org/getting-started/#add-a-chart

version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  # create a new action called describe
  describe:
    # run the script (using the python or R runner
    run: r:latest analysis/report.R
    # this action depends on the outputs of the generate_study_population being present
    needs: [generate_study_population]
    outputs:
      # describe the files that the action creates. 
      # the items indented below it are moderately sensitive, 
      #   that is they may be released to the public after a careful review 
      #   (and possible redaction
      moderately_sensitive:
        # there's one output file, which will be found at output/descriptive.png.
        cohort: output/descriptive.png
